### ISSUE TITLE
Messages not appearing in Civi

### ISSUE THREAD

**Issue by summerse** [3sd/civicrm-chatbot#10] opened 2018-06-07 18:27 UTC
Hey @michaelmcandrew we have successfully set things up without errors, but the messages that are sent (via FB messenger) are not appearing at all in Civi. We also don't appear to see any activity trigger in CiviRules for chat conversations.

These two issues (especially the first one) are preventing us from testing/validating that it works. Thanks!

**Comment by michaelmcandrew** [comment] 2018-06-12 16:59
hi @summerse can you expand on "we have successfully set things up without errors". Does that mean you have entered credentials and they saved OK here: https://chatbot.demo.3sd.io/civicrm/admin/chat/facebook.

Looking at your credentials, I am not sure that they are correct. The facebook app secret is the same as for my my app. @stigsfoot - could you take a look ***and send me your app secret via email or similar*** so I can add it to the deploy script.

Re: the trigger for chat conversations, Conversations are now activity types and you should be able to use a 'Activity is added' trigger with a condition along the lines of 'Activity is (not) one of type(s) | Activity Type is one of: Conversation'

I experienced issue #8 and have has some success in reproducing. It seems to be related to enabling and uninstalling other extensions. I'll continue to investigate and keep you up to date.

**Comment by summerse** [comment] 2018-06-15 13:45
@michaelmcandrew regarding the trigger for chat conversations - it seems as though we'd need the condition to activity is one of an inbound chat. And then the linked action would be to trigger a conversation. And conversation still does not appear as an option in the "Select action" list. Unless I'm somehow still missing something, I'm not sure otherwise how we'd determine which conversation gets triggered based upon an incoming chat.

**Comment by michaelmcandrew** [comment] 2018-06-18 20:49
hi @summerse, i'm closing this and opening https://github.com/3sd/civicrm-chatbot/issues/11 as a seperate issue. will get back to you on that shortly.

**Closed as completed by michaelmcandrew** 2018-06-18 20:49 UTC
