### ISSUE TITLE
Unable to save Facebook settings in Civi

### ISSUE THREAD

**Issue by stigsfoot** [3sd/civicrm-chatbot#9] opened 2018-06-04 18:58 UTC
Possibly linked to #8 , When re-entering records due to possibly malformed? data _(missing previously entered settings)_ Admin user gets a CiviAdmin error described to the right

**Comment by michaelmcandrew** [comment] 2018-06-06 09:19
closing as duplicate of #8 (let me know if I am mistaken)

**Closed as completed by michaelmcandrew** 2018-06-06 09:19 UTC
