### ISSUE TITLE
Issue preventing FB setting saves from persisting

### ISSUE THREAD

**Issue by stigsfoot** [3sd/civicrm-chatbot#8] opened 2018-06-04 18:45 UTC
When saving Facebook Settings, settings do not persist thus preventing a new integration from being created.

- [Feedback sheet {issue 10}](https://docs.google.com/spreadsheets/d/1l2_z8bqhrudJuOSuWcm17S1zHZ-QMFjMvChiHoIVisc/edit#gid=0)
- [Screenshot ](https://drive.google.com/open?id=1MGhDDupyFiVy5Q5Y0Bl0llW4V53iK0V1)

**Comment by michaelmcandrew** [comment] 2018-06-06 09:18
@stigsfoot - lets continue the conversation here rather than in the google drive since this interface is built for issue tracking.

I've seen the issue a couple of times but have not been able to reliably reproduce as yet. A bit of background:

The extension defines some settings using the standard mechanism. When you save that form it should update the settings. This works for me on the demo server after a fresh install. But coming back to the demo a few days later, I see the same errors as you:

```
"Notice: Undefined index: chatbot_facebook_verify_token in CRM_Chat_Form_Admin_Facebook->initFields() (line 43 of /home/ubuntu/buildkit/build/chatbot/sites/all/modules/civicrm/tools/extensions/civicrm-chatbot/CRM/Chat/Form/Admin/Facebook.php).
User deprecated function: Deprecated Path: There is a setting (chatbot_facebook_verify_token) not correctly defined. You may see unpredictability due to this. CRM_Core_Setting::setItems Array ( [civi.tag] => deprecated ) in CRM_Core_Error_Log->log() (line 69 of /home/ubuntu/buildkit/build/chatbot/sites/all/modules/civicrm/CRM/Core/Error/Log.php).
Notice: Undefined index: type in CRM_Core_BAO_Setting::validateSetting() (line 294 of /home/ubuntu/buildkit/build/chatbot/sites/all/modules/civicrm/CRM/Core/BAO/Setting.php)."
```
Checking via the settings API, I see that they have indeed been undefined but I am not sure what the cause is.

Could you please try and update the settings again on the demo and see if the same thing happens? Please refrain from making any other changes. Let me know if it works / does not work for you and I will take a look in the logs.

**Comment by stigsfoot** [comment] 2018-06-07 16:38
Take a look at the logs The settings seem to update now without error. 
Had you changed anything technically (other than restoring the previous settings?) 
Also, any thoughts on the cause now?

**Comment by michaelmcandrew** [comment] 2018-06-07 16:58
I also logged in and made a couple of updates, which I have now reverted, and the form saved OK.

Since this all worked OK, there won't be anything interesting to see in the logs.

I had not made any changes to the code. I made a couple of tweaks to the deployment script. That may have made a difference.

For now, I am going to assume that the most likely cause was something odd happening in the [deployment scripts](https://github.com/3sd/civicrm-chatbot/tree/master/chatbot-demo) rather than any issues with the extension code itself and close this issue.

If the issue recurs, we can re-open it.

Aside: In case this is useful in the future, I reached on for a second opinion on why this might be happening here: https://chat.civicrm.org/civicrm/pl/8iokjoxf8jf5iewae1kb5f5g6y

> michaelmcandrew
10:03 AM
i am scratching my head on the following. I have an extension that as far as I know correctly defines settings. They install correctly. After a while, they become deregistered. i.e. cv api setting.get shows them as missing. calling cv flush makes them reappear. i can't work out what is causing them to disappear. it's like they wait until I am not looking.

> totten
7:01 PM
Dunno. Sounds like there’s some circumstance in which the cache isn’t rehydrated completely. For example... (a) maybe there’s a backend script in which it flushes/rehydrates but which doesn’t have all the extensions activated (b) maybe there’s a race in which the alter hook fires before the extensions are fully online or (c) maybe there’s some “optimized” scenario where it tries to flush/rehydrate one part of the metadata... but actually flushes everything.

This makes me think that possibly the issue may be due to interaction with another (badly behaving?) extension.

**Comment by michaelmcandrew** [comment] 2018-06-11 22:52
@stigsfoot - I am re-opening as this happened again. Currently investigating...

**Comment by stigsfoot** [comment] 2018-06-12 18:58
Let me know if there's an update with this @michaelmcandrew . I hope all is well.

**Comment by michaelmcandrew** [comment] 2018-06-13 07:01
will do @stigsfoot. in the mean time, can you look at https://github.com/3sd/civicrm-chatbot/issues/10#issuecomment-396661692 and send me the app credentials please.

**Comment by michaelmcandrew** [comment] 2018-06-13 10:15
That way you can continue testing the rest of the app while I work on this.

**Comment by michaelmcandrew** [comment] 2018-06-13 11:48
I tracked down a fairly obscure bug in civicrm-core and civix that was causing this. See https://github.com/totten/civix/issues/139

**Comment by michaelmcandrew** [comment] 2018-06-13 12:04
@stigsfoot - this should now be fixed with https://github.com/3sd/civicrm-chatbot/commit/c421332895dad5606580c60bc228a35ba46207a3 which is now deployed at https://chatbot.demo.3sd.io/

**Comment by stigsfoot** [comment] 2018-06-17 13:24
I've been following along. Thanks for tracking that down. Will test this week.

**Comment by michaelmcandrew** [comment] 2018-07-26 14:22
closing - this is now fixed

**Closed as completed by michaelmcandrew** 2018-07-26 14:22 UTC
